### PR TITLE
solved issue#96

### PR DESCRIPTION
**Pull request by divyansh14kr**
the navbar items all line up properly now.
Screenshot 2023-10-25 at 3 35 02 PM

### CODE REVIEW

**Review by arpankumarde — APPROVED** [review]

**Review by arpankumarde — CHANGES_REQUESTED** [review]
Hi there, thank you for your contribution to this project. 👏

I have reviewed your pull request and I have some feedback and suggestions for improvement.

- The navlinks are currently aligned to the left of the navbar. It would be great if we could align them to the right instead. This would not only make the layout more consistent, but also more aesthetically pleasing. To achieve this, you can use the `flexbox` properties in CSS.
- Additionally, I recommend checking the responsiveness of the navbar in standard device sizes. To address this, you can use media queries to adjust the style and behavior of the navbar for different screen sizes. 

Please let me know if you have any questions or need any help with these changes. I appreciate your effort and I look forward to seeing your updated pull request. 😊

**Comment by divyansh14kr** [comment]
something like this?
Screenshot 2023-10-26 at 11 04 14 PM

**Review by arpankumarde — APPROVED** [review]
Yes, Now the Navbar looks better

**Comment by divyansh14kr** [comment]
added the above changes to the player
please approve

**Review by arpankumarde — APPROVED** [review]
Good to go!

**Comment by divyansh14kr** [comment]
hey, when will it get merged? I need it for hacktober fest

**Comment by arpankumarde** [comment]
@samratghosh291 da, please look into it

**Pull request merged**
