### PR TITLE
Issue No. #49 [BUG FIXED] In the footer section, the copyright year should be dynamically generated instead of being statically hardcoded.

### LINKED ISSUE #49: [BUG] In the footer section, the copyright year should be dynamically generated instead of being statically hardcoded.
**Screenshot**

Screenshot 2023-10-07 233815

Screenshot 2023-10-07 233925

--------------------

@samratghosh291 Right now, the copyright year is written manually, which means someone has to change it whenever a new year begins. However, with just a few lines of code in JavaScript, we can make it automatic. This means that the copyright year will always be up-to-date without anyone having to change it manually. For example, if the current year is 2023, the copyright section will show 2023. And when the year changes to 2024, the copyright section will automatically update to 2024.

### PR DESCRIPTION
**Pull request by gauravsingh1281**
Closes #49

### CODE REVIEW

**Comment by samratghosh291** [comment]
please resolve the conflict

**Comment by samratghosh291** [comment]
Thank you for your contribution 😊

**Review by samratghosh291 — APPROVED** [review]

**Comment by gauravsingh1281** [comment]
@samratghosh291 Please assign this pull request to me and add **hacktoberfest-accepted** label.

**Comment by gauravsingh1281** [comment]
@samratghosh291 Please assign this pull request to me and add hacktoberfest-accepted label.

**Pull request merged**
